#include<stdio.h>
#include<conio.h>
int main()
{
    int i,j,s,k,a[3][3],b[3][3],c[3][3];
    printf("enter element first matrix\n");
    for(i=0;i<3;i++)
    {
        for(j=0;j<3;j++)
        {
            scanf("%d",&a[i][j]);
        }
        printf("\n");
    }
    printf("\n");
    printf("enter element second matrix\n");
    for(i=0;i<3;i++)
    {
        for(j=0;j<3;j++)
        {
            scanf("%d",&b[i][j]);
        }
        printf("\n");
    }
    printf("\n");
    for(i=0;i<3;i++)
    {
        for(j=0;j<3;j++)
        {
            printf("%d\t",a[i][j]);
        }
        printf("\n");
    }
    printf("\n");
    for(i=0;i<3;i++)
    {
        for(j=0;j<3;j++)
        {
            printf("%d\t",b[i][j]);
        }
        printf("\n");
    }
   printf("\nmultiplication\n");
    for(i=0;i<3;i++)
    {
        for(j=0;j<3;j++)
        {
            s=0;
            for(k=0;k<3;k++)
            {
                s=s+a[i][k]*b[k][j];
            }
            c[i][j]=s;
            printf("%d\t",c[i][j]);
        }
        printf("\n");
    }
    getch();
}